# Generated by Django 4.2.7 on 2023-11-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
